name: telosnex_audio_example
description: Development app for telosnex_audio.
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  telosnex_audio:
    path: ..
  web: ^1.1.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/speech.mp3
