// Prebuilt native libraries published by .github/workflows/release.yml.
// Generated by tool/write_prebuilt_manifest.dart. Do not edit.
//
// The hook downloads a prebuilt only when the package's native source hash
// equals [prebuiltSourceHash]. Otherwise it builds from source.

// dart format off
const String? prebuiltReleaseTag = null;
const String prebuiltSourceHash = '';
const Map<String, String> prebuiltSha256 = {};
