// Prebuilt native libraries published by .github/workflows/release.yml.
// Generated by tool/write_prebuilt_manifest.dart. Do not edit.
//
// The hook downloads a prebuilt only when the package's native source hash
// equals [prebuiltSourceHash]. Otherwise it builds from source.

// dart format off
// Nullable getter: unpublished manifests may return null.
String? get prebuiltReleaseTag => 'native-0cea6fb2a649c23a';
const String prebuiltSourceHash = '0cea6fb2a649c23ae2e5139f4c2ef598d47497eaa848f357bdf327072d415a49';
const Map<String, String> prebuiltSha256 = {
  'linux-arm64/libtelosnex_audio.so': 'f06e6d3fadaaba1cc2f603be6a7c40ef8d9de53f5c20614b01ee3642ea1853d9',
  'linux-x64/libtelosnex_audio.so': 'b2b13fae8042ef24f6303c72a5f3bb5599484dca1a80ddb876dd9d3a6e9bd875',
  'macos-arm64/libtelosnex_audio.dylib': '762afbc6e4f2a2aa931432d21ee150674cc0c124f9c8f5d86114982e36431947',
  'macos-x64/libtelosnex_audio.dylib': '7aaa0efe3b5daef85e360b800610fa9e9e195127dd66685c26f1859145c2d3c2',
  'windows-arm64/telosnex_audio.dll': 'be052e57d5b97649628677536068bc9759981b9ddb1a6bcfd1c14954955a3e5d',
  'windows-x64/telosnex_audio.dll': '8e3f5f1fdfcb28eeece25642262cbe7f5f4d89ee128c235f7f354dc7c07ad167',
};
