// Writes lib/src/hook/prebuilt.g.dart for a published prebuilt release.
//
// Run with the VM directly after `flutter pub get`, so this metadata-only
// tool does not invoke the package's native build hook:
//
//   dart --disable-dart-dev --packages=.dart_tool/package_config.json \
//     tool/write_prebuilt_manifest.dart --assets <dir>
//   dart --disable-dart-dev --packages=.dart_tool/package_config.json \
//     tool/write_prebuilt_manifest.dart --print-hash | --print-tag
//
// The release tag is `native-` and the first 16 hex digits of the native
// source hash, as in image_ffmpeg, fllama and zxing_dart. The tag names the
// source that the files were built from.
// <dir> holds files named `<os>-<arch>-<library file>`, for example
// `macos-arm64-libtelosnex_audio.dylib`, exactly as uploaded to the release.
import 'dart:io';

import 'package:crypto/crypto.dart';
import 'package:telosnex_audio/src/hook/native_build.dart';

void main(List<String> args) {
  final root = Directory(File.fromUri(Platform.script).parent.parent.path);
  final hash = nativeSourceHash(root, nativeSourceFiles(root));
  final tag = 'native-${hash.substring(0, 16)}';
  if (args.contains('--print-hash')) {
    stdout.writeln(hash);
    return;
  }
  if (args.contains('--print-tag')) {
    stdout.writeln(tag);
    return;
  }
  String? assets;
  for (var i = 0; i < args.length; i++) {
    if (args[i] == '--assets') assets = args[++i];
  }
  if (assets == null) {
    stderr.writeln('usage: --assets <dir> | --print-hash | --print-tag');
    exit(64);
  }
  final entries = <String, String>{};
  final files = Directory(assets).listSync().whereType<File>().toList()
    ..sort((a, b) => a.path.compareTo(b.path));
  for (final f in files) {
    final name = f.uri.pathSegments.last;
    final dash = name.indexOf('-', name.indexOf('-') + 1);
    if (dash < 0) continue;
    final key = '${name.substring(0, dash)}/${name.substring(dash + 1)}';
    entries[key] = sha256.convert(f.readAsBytesSync()).toString();
  }
  final out = StringBuffer()
    ..writeln(
      '// Prebuilt native libraries published by '
      '.github/workflows/release.yml.',
    )
    ..writeln('// Generated by tool/write_prebuilt_manifest.dart. Do not edit.')
    ..writeln('//')
    ..writeln(
      "// The hook downloads a prebuilt only when the package's native "
      'source hash',
    )
    ..writeln(
      '// equals [prebuiltSourceHash]. Otherwise it builds from source.',
    )
    ..writeln()
    ..writeln('// dart format off')
    ..writeln('// Nullable getter: unpublished manifests may return null.')
    ..writeln("String? get prebuiltReleaseTag => '$tag';")
    ..writeln("const String prebuiltSourceHash = '$hash';")
    ..writeln('const Map<String, String> prebuiltSha256 = {');
  for (final e in entries.entries) {
    out.writeln("  '${e.key}': '${e.value}',");
  }
  out.writeln('};');
  File(
    '${root.path}/lib/src/hook/prebuilt.g.dart',
  ).writeAsStringSync(out.toString());
  stdout.writeln('Wrote ${entries.length} prebuilt entries for $tag ($hash).');
}
